adjust cloudbuild

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -17,6 +17,45 @@ steps:
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/expenses-backend']
   dir: 'backend'
+
+# Migration steps
+- id: 'Start Cloud SQL Proxy'
+  name: 'gcr.io/cloud-builders/docker'
+  args:
+    - 'run'
+    - '-d'
+    - '--network=cloudbuild'
+    - '--name=cloudsql-proxy'
+    - 'gcr.io/cloudsql-connectors/cloud-sql-proxy'
+    - ${_INSTANCE_CONNECTION_NAME}
+    - '--port=5432'
+    - '--address=0.0.0.0'
+- id: 'Check Proxy Health & Wait'
+  name: 'bash'
+  args:
+    - '-c'
+    - |
+      echo "Waiting 10 seconds for proxy to initialize..."
+      sleep 10
+      echo "Displaying proxy logs (check for 'permission denied' or 'instance not found'):"
+      docker logs cloudsql-proxy || true
+- id: 'Run Database Migrations'
+  name: 'golang:latest'
+  entrypoint: 'sh'
+  args:
+    - '-c'
+    - |
+      go install github.com/golang-migrate/migrate/cmd/migrate@latest
+      
+      /root/go/bin/migrate -path file://backend/cmd/migrate/migrations -database "postgres://${_DB_USER}:${_DB_PASSWORD}@cloudsql-proxy:5432/${_DB_NAME}?sslmode=disable" up
+- id: 'Stop Cloud SQL Proxy'
+  name: 'gcr.io/cloud-builders/docker'
+  args:
+    - 'stop'
+    - 'cloudsql-proxy'
+  waitFor: ['-']
+
+# Cloud run deployment steps
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: 'bash'
   args:
@@ -45,42 +84,6 @@ steps:
     - '--add-cloudsql-instances=$PROJECT_ID:asia-southeast1:expenses-db'
     - '--env-vars-file=env_secrets.env'
     - '--allow-unauthenticated'
-- id: 'Start Cloud SQL Proxy'
-  name: 'gcr.io/cloud-builders/docker'
-  args:
-    - 'run'
-    - '-d' # Run in detached mode (background)
-    - '--network=cloudbuild' # Use the internal Cloud Build network
-    - '--name=cloudsql-proxy'
-    - 'gcr.io/cloudsql-connectors/cloud-sql-proxy'
-    - ${_INSTANCE_CONNECTION_NAME}
-    - '--port=5432'
-    - '--address=0.0.0.0' # Listen only on the local interface (required for the next step)
-- id: 'Check Proxy Health & Wait'
-  name: 'bash'
-  args:
-    - '-c'
-    - |
-      echo "Waiting 10 seconds for proxy to initialize..."
-      sleep 10
-      echo "Displaying proxy logs (check for 'permission denied' or 'instance not found'):"
-      docker logs cloudsql-proxy || true
-- id: 'Run Database Migrations'
-  name: 'golang:latest'
-  entrypoint: 'sh'
-  args:
-    - '-c'
-    - |
-      go install github.com/golang-migrate/migrate/cmd/migrate@latest
-      
-      /root/go/bin/migrate -path file://backend/cmd/migrate/migrations -database "postgres://${_DB_USER}:${_DB_PASSWORD}@cloudsql-proxy:5432/${_DB_NAME}?sslmode=disable" up
-- id: 'Stop Cloud SQL Proxy'
-  name: 'gcr.io/cloud-builders/docker'
-  args:
-    - 'stop'
-    - 'cloudsql-proxy'
-  # This step should run even if the migration failed, so we use `always` execution.
-  waitFor: ['-']
 
 options:
   logging: CLOUD_LOGGING_ONLY
